name: SSHX Session

on:
  workflow_dispatch:

jobs:
  run-sshx:
    runs-on: ubuntu-latest

    steps:
      - name: Start SSHX live terminal
        run: |
          curl -sSf https://sshx.io/get | sh -s run
