name: Start SSHX Session

on:
  workflow_dispatch:

jobs:
  sshx:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshx
        run: |
          curl -sSf https://sshx.io/install.sh | sh

      - name: Start sshx session
        run: |
          ~/.sshx/sshx
